### ISSUE TITLE
Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by chief-j** [TheIndra55/SpigotBoard#7]
Plugin is not working and I can not understand why
`[19:08:42 ERROR]: Could not pass event PlayerJoinEvent to SpigotBoard v1.0.4
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/entity/CraftPlayer
        at eu.theindra.krille.Information.PlaceHolders.GetPing(PlaceHolders.java:25) ~[?:?]
        at eu.theindra.krille.Events.ScoreboardManager.Addscoreboard1(ScoreboardManager.java:64) ~[?:?]
        at eu.theindra.krille.Events.ScoreboardManager.Addscoreboard(ScoreboardManager.java:28) ~[?:?]
        at eu.theindra.krille.Events.OnJoin.onJoin(OnJoin.java:11) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-741]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-741]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-741]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-741]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:349) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:175) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:917) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-741]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.9.4.jar:git-Paper-741]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.9.4.jar:git-Paper-741]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
        ... 21 more
[19:08:42 INFO]: chief[/127.0.0.1:4595] logged in with entity id 146 at ([world]262.1314435172917, 89.0, 232.12153229446997)`

----------------------------

`[19:08:43 WARN]: [SpigotBoard] Task #19 for SpigotBoard v1.0.4 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/entity/CraftPlayer
        at eu.theindra.krille.Information.PlaceHolders.GetPing(PlaceHolders.java:25) ~[?:?]
        at eu.theindra.krille.Events.ScoreboardManager.Addscoreboard1(ScoreboardManager.java:64) ~[?:?]
        at eu.theindra.krille.Events.ScoreboardManager.Addscoreboard(ScoreboardManager.java:28) ~[?:?]
        at eu.theindra.krille.scoreboard.Main$1.run(Main.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-741]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:827) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-741]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-741]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

**Comment by TheIndra55** [comment]
What version of spigtboard do you have, And what version of bukkit?

**Comment by chief-j** [comment]
In logs all written
Your plugin was for R1 and I had R2 (core build)
